[[headers]]
  for = ";/PC-Simulator-Save-Editor-2/Build/Build.data.gz"
  [headers.values]
    Content-Encoding = ";gz"
    Content-Type = ";gzip"

[[headers]]
  for = ";/PC-Simulator-Save-Editor-2/Build/Build.framework.js.gz"
  [headers.values]
    Content-Encoding = ";gz"
    Content-Type = ";gzip"

[[headers]]
  for = ";/PC-Simulator-Save-Editor-2/Build/Build.wasm.gz"
  [headers.values]
    Content-Encoding = ";gz"
    Content-Type = ";gzip"